import { controllerDependency, sockJs } from '../src-snippets';

import { ElementDeclaration } from '../../code-gen';
import { PieTarget } from '../../install';

export default function js(
  declarations: ElementDeclaration[],
  controllers: PieTarget[],
  sockPath: string) {

  return `
/** Auto generated by ${__filename} */

//pie controllers 
let controllers = {};
${controllers.map(controllerDependency).join('\n')}

//pie declarations
${declarations.map(e => e.js).join('\n')}

// the catalog ui
import CatalogDemo from 'pie-catalog-client/src/catalog-demo';
customElements.define('catalog-demo', CatalogDemo);
import ItemPreview from 'pie-catalog-client/src/catalog-demo/item-preview';
customElements.define('item-preview', ItemPreview);
import ControlPanel from 'pie-catalog-client/src/catalog-demo/control-panel';
customElements.define('control-panel', ControlPanel);

require('pie-catalog-client/src/common.less');
require('material-elements/src/select-field');

let initSock = ${sockJs()}

let init = () => {

  let allPromises = [
    customElements.whenDefined('catalog-demo')
  ];

  Promise.all(allPromises)
    .then(() => {
      let demo = document.querySelector('catalog-demo');
      demo.config = window.demo.config;
      demo.controllers = controllers;
      demo.markup = window.demo.markup;
    });

    initSock('${sockPath}');
}

document.addEventListener('DOMContentLoaded', () => {
  init();
}); `;
}
