import Question from '../question';
import { resolve } from 'path';
import { buildLogger } from '../log-factory';
import { join } from 'path';
import { removeSync } from 'fs-extra';
import { PackQuestionOpts } from './pack-question';

const marked = require('marked');
const TerminalRenderer = require('marked-terminal');

let logger = buildLogger();

export function match(args) {
  return args._.indexOf('clean-question') !== -1;
}

export let summary = 'clean-question - remove files generated by the `pack-question` command';

marked.setOptions({
  renderer: new TerminalRenderer()
});

export let usage = marked(`
# clean-question 
-----------------

Clean the cruft generated by pack-question 

### Examples 

\`\`\`shell 
pie-cli clean-question --dir ../path/to/dir

`);

export function run(args) {
  logger.debug('[run] args: ', args);
  let dir = resolve(args.dir || process.cwd());

  //Note: we don't need an app when cleaning
  let emptyApp = {
    frameworkSupport: () => []
  };

  //Note: we don't need framework support for a clean
  let noExternalSupport = [];
  let questionOpts = Question.buildOpts(args);
  let packOpts = PackQuestionOpts.build(args);
  let question = new Question(dir, questionOpts, noExternalSupport, emptyApp);
  return question.clean()
    .then(() => removeSync(join(dir, packOpts.exampleFile)))
    .then(() => "clean complete")
}