import Question from '../question';
import { resolve } from 'path';
import { buildLogger } from '../log-factory';
import { join } from 'path';
import { removeSync } from 'fs-extra';
import { PackQuestionOpts } from './pack-question';
import CliCommand from './cli-command';

let logger = buildLogger();

class CleanQuestionCommand extends CliCommand {
  constructor() {
    super('clean-question', 'Clean the cruft generated by pack-question');
  }

  run(args) {
    logger.debug('[run] args: ', args);
    let dir = resolve(args.dir || process.cwd());

    //Note: we don't need an app when cleaning
    let emptyApp = {
      frameworkSupport: () => []
    };

    //Note: we don't need framework support for a clean
    let noExternalSupport = [];
    let questionOpts = Question.buildOpts(args);
    let packOpts = PackQuestionOpts.build(args);
    let question = new Question(dir, questionOpts, noExternalSupport, emptyApp);
    return question.clean()
      .then(() => removeSync(join(dir, packOpts.exampleFile)))
      .then(() => "clean complete")
  }
}
let cmd = new CleanQuestionCommand();
export default cmd;